[window]
width_percent = 20 # width with respect to the screen
height_percent = 55 # height with respect to the screen
screen_selector = 0 # for multi-monitor setup (buggy!)
# initial window placement (-1 for extreme end (right or bottom for x or y respectively))
x = -1
y = 0

[theme]
opacity = 85 # in percent
background_colour = "#000000" # only hex-codes work for now
text_colour = "#FFFFFF"
font_size = 22
font_style = "Consolas" # limited font selection for now
future_opacity_percent = 50 # upcoming lyric
past_opacity_percent = 100 # past lyric

[keybinds]
# Use '<cmd>' for the Super/Meta (or Windows) key
show_hide = "<ctrl>+<cmd>+k"

[behaviour]
allow_dragging = true
allow_minimise = false
allow_maximise = false
allow_closing = false
snap_threshold_percent = 2.5

[other]
linux_cache_location = "~/.cache/LyricOverlay/"
acceptable_duration_difference = 1.0 # used for matching online lyrics. in seconds